name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: the environment being deployed to
        required: true
    secrets:
      SERVER_ENVIRONMENT:
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world! ${{ secrets.SERVER_ENVIRONMENT }}
