name: Deploy Development 

on:
  workflow_dispatch:

jobs:
  publish-development:
    name: publish development
    uses: ./.github/workflows/main.yml
    with:
      environment: development
    secrets: inherit
