name: Upload a Build Artifact
on:
  workflow_dispatch
jobs: 
  artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: node -v
      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/world.txt

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: my-artifact
          path: path/to/artifact/world.txt
